name: Python application

on:
  push:
    branches:
      - main
  

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
    - name: Create github release
      uses: actions/checkout@v3
    uses: actions/create-release@v1
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      tag_name: ${{ github.ref_name }}
      release_name: Release ${{ github.ref_name }}
      body: |
        blablabla
      draft: false
      prerelease: false
